#!/bin/sh

set -e

usage() {
  printf '%s [-x cross_prefix] [-r rootfs_prefix] [-c]\n' $0
  exit 1
}

reqs() {
  local b
  local missing

  for b in cc c++ make patch tar xz curl file m4 ed; do
    which $b >/dev/null 2>&1 || missing="$missing $b"
  done

  if [ "$missing" ]; then
    printf "need '%s'\n" $missing
    exit 1
  fi
}

fetch() {
  local deps='
    binutils
    gmp
    mpfr
    mpc
    gcc
    linux-headers
    musl
    busybox
    make
    xz
    file
  '
  local d

  for d in $deps; do
    ./mk fetch $d
  done
}

manual_install() {
  local prefix=$1
  local name=$2

  tar -C $prefix -xJf repo/$(./mk query $name fullname).tar.xz
}

rootfs_install() {
  local name=$1
  manual_install $ROOTFS_PREFIX $name
}

build_gcc() {
  local name=$1
  local prefix=$2

  ./mk extract $name

  local dep dest
  for dep in gmp mpfr mpc; do
    ./mk extract $dep
    dest=$(./mk query $name MK_DIST)/$dep
    [ -h $dest ] || ln -s $(./mk query $dep MK_DIST) $dest
  done

  MK_PREFIX=$prefix \
  MK_CONFIGURE="--prefix=$prefix" \
  MK_DESTDIR=no \
    ./mk install $name
}

cross() {
  local prefix=$CROSS_PREFIX

  if ! [ -e $prefix/$TRIPLE/usr ]; then
    mkdir -p $prefix/$TRIPLE
    ln -s . $prefix/$TRIPLE/usr
  fi

  if ! [ -x $prefix/bin/pkg-contain ]; then
    MK_PREFIX=$prefix \
    MK_DESTDIR=no \
      ./mk install bootstrap-pkg
  fi

  ./mk pkg linux-headers
  if ! [ -e $prefix/$TRIPLE/include/linux/inotify.h ]; then
    manual_install $prefix/$TRIPLE linux-headers
    mv $prefix/$TRIPLE/usr/include $prefix/$TRIPLE
    rmdir $prefix/$TRIPLE/usr
  fi

  if ! [ -x $prefix/bin/$TRIPLE-ar ]; then
    MK_PREFIX=$prefix \
    MK_CONFIGURE="--prefix=$prefix" \
    MK_DESTDIR=no \
      ./mk install bootstrap-binutils
  fi

  if ! [ -x $prefix/bin/$TRIPLE-gcc ]; then
    build_gcc bootstrap-gcc-1 $prefix
  fi


  if ! [ -e $prefix/$TRIPLE/include/stdio.h ]; then
    MK_PREFIX=$prefix/$TRIPLE \
    CROSS_COMPILE=$TRIPLE- \
    CC=$TRIPLE-gcc \
    MK_CONFIGURE="--prefix=$prefix/$TRIPLE" \
    MK_DESTDIR=no \
      ./mk install bootstrap-musl
  fi

  if ! [ -x $prefix/bin/$TRIPLE-g++ ]; then
    build_gcc bootstrap-gcc-2 $prefix
  fi
}

rootfs() {
  local prefix=$ROOTFS_PREFIX/usr

  export CC=$TRIPLE-gcc
  export CXX=$TRIPLE-g++
  export AR=$TRIPLE-ar
  export AS=$TRIPLE-as
  export LD=$TRIPLE-ld
  export RANLIB=$TRIPLE-ranlib
  export READELF=$TRIPLE-readelf
  export STRIP=$TRIPLE-strip

  ./mk pkg musl
  if ! [ -e $prefix/include/stdio.h ]; then
    rootfs_install musl
  fi

  ./mk pkg linux-headers
  if ! [ -e $prefix/include/linux/inotify.h ]; then
    rootfs_install linux-headers
  fi

  CROSS_COMPILE=$TRIPLE- \
    ./mk pkg busybox
  if ! [ -x $ROOTFS_PREFIX/bin/busybox ]; then
    rootfs_install busybox
  fi

  ./mk pkg sbase
  if ! [ -x $ROOTFS_PREFIX/usr/bin/cp ]; then
    rootfs_install sbase
  fi

  ./mk pkg ubase
  if ! [ -x $ROOTFS_PREFIX/usr/bin/passwd ]; then
    rootfs_install ubase
  fi

  ./mk pkg ksh
  if ! [ -x $ROOTFS_PREFIX/bin/sh ]; then
    rootfs_install ksh
  fi

  ./mk pkg ed
  if ! [ -x $ROOTFS_PREFIX/usr/bin/ed ]; then
    rootfs_install ed
  fi

  ./mk pkg awk
  if ! [ -x $ROOTFS_PREFIX/usr/bin/awk ]; then
    rootfs_install awk
  fi

  ./mk pkg bzip2
  if ! [ -x $ROOTFS_PREFIX/usr/bin/bzip2 ]; then
    rootfs_install bzip2
  fi

  MK_BUILD_TRIPLE=$(gcc -dumpmachine) \
  MK_CONFIGURE="--prefix=/usr" \
    ./mk pkg binutils
  if ! [ -x $ROOTFS_PREFIX/usr/bin/ar ]; then
    rootfs_install binutils
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr" \
    ./mk pkg gmp
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libgmp.so ]; then
    rootfs_install gmp
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr
    --with-gmp=$prefix" \
    ./mk pkg mpfr
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libmpfr.so ]; then
    rootfs_install mpfr
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr
    --with-gmp=$prefix
    --with-mpfr=$prefix" \
    ./mk pkg mpc
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libmpc.so ]; then
    rootfs_install mpc
  fi

  MK_BUILD_TRIPLE=$(gcc -dumpmachine) \
  MK_CONFIGURE="
    --prefix=/usr
    --with-gmp=$prefix
    --with-mpfr=$prefix
    --with-mpc=$prefix" \
    ./mk pkg gcc
  if ! [ -x $ROOTFS_PREFIX/usr/bin/gcc ]; then
    rootfs_install gcc
  fi

  local bin
  for bin in make xz file; do
    MK_CONFIGURE="
      --host=$TRIPLE
      --prefix=/usr" \
      ./mk pkg $bin
    if ! [ -x $ROOTFS_PREFIX/usr/bin/$bin ]; then
      rootfs_install $bin
    fi
  done

  ./mk pkg hier
  if ! [ -d $ROOTFS_PREFIX/dev ]; then
    rootfs_install hier
  fi

  ./mk pkg pkg
  if ! [ -d $ROOTFS_PREFIX/pkg-contain ]; then
    rootfs_install pkg
  fi
}

contain() {
  local conf=$ROOTFS_PREFIX/etc/pkg.conf

  printf 'REPO=%s\n' /host/repo > $conf

  env -i \
    PATH="/usr/bin:/usr/sbin:/bin:/sbin" \
    PS1='[bootstrap] \w \$ ' \
    HOSTDIR=$(pwd) \
    $CROSS_PREFIX/bin/pkg-contain $ROOTFS_PREFIX /bin/sh

  rm -f $conf
}

while getopts "r:x:ch" opt; do
  case $opt in
    x)
      CROSS_PREFIX=$OPTARG
      ;;
    r)
      ROOTFS_PREFIX=$OPTARG
      ;;
    c)
      CONTAIN=yes
      ;;
    h)
      usage
      ;;
  esac
done
unset opt

: ${CROSS_PREFIX:=$HOME/bare-cross}
: ${ROOTFS_PREFIX:=$HOME/bare-rootfs}

TRIPLE=$(./mk query gcc MK_TARGET_TRIPLE)
PATH=$CROSS_PREFIX/bin:$PATH

if [ "$CONTAIN" ]; then
  contain
else

  mkdir -p $CROSS_PREFIX $ROOTFS_PREFIX

  reqs
  fetch
  cross
  rootfs
fi
