#!/bin/sh

set -e

usage() {
  cat <<EOF
$0 -x <cross prefix> -r <rootfs prefix>

Example:

    $0 -x /tmp/xunil-cross -r /tmp/xunil-rootfs
EOF
  exit 1
}

reqs() {
  local b
  local missing

  for b in cc c++ make patch tar xz curl perl file m4; do
    which $b >/dev/null 2>&1 || missing="$missing $b"
  done

  if [ "$missing" ]; then
    printf "need '%s'\n" $missing
    exit 1
  fi
}

build_gcc() {
  local name=$1
  local prefix=$2

  ./mk extract $name

  local dep dest
  for dep in gmp mpfr mpc; do
    ./mk extract $dep
    dest=$(./mk query $name MK_SRC)/$dep
    [ -h $dest ] || ln -s $(./mk query $dep MK_SRC) $dest
  done

  MK_PREFIX=$prefix \
  MK_CONFIGURE="
    --prefix=$prefix
    --target=$TRIPLE" \
  MK_DESTDIR=no \
    ./mk install $name
}

cross() {
  local prefix=$CROSS_PREFIX/$TRIPLE

  if ! [ -e $prefix/$TRIPLE/usr ]; then
    mkdir -p $prefix/$TRIPLE
    ln -s . $prefix/$TRIPLE/usr
  fi

  if ! [ -x $prefix/bin/$TRIPLE-ar ]; then
    MK_PREFIX=$prefix \
    MK_CONFIGURE="
      --prefix=$prefix
      --target=$TRIPLE" \
    MK_DESTDIR=no \
      ./mk install bootstrap-0-binutils
  fi

  if ! [ -x $prefix/bin/$TRIPLE-gcc ]; then
    build_gcc bootstrap-0-gcc-1 $prefix
  fi

  if ! [ -e $prefix/$TRIPLE/include/linux/inotify.h ]; then
    MK_DESTDIR=$prefix \
    MK_PREFIX=$TRIPLE \
      ./mk install bootstrap-0-linux-headers
  fi

  if ! [ -e $prefix/$TRIPLE/include/stdio.h ]; then
    MK_PREFIX=$prefix/$TRIPLE \
    CROSS_COMPILE=$TRIPLE- \
    CC=$TRIPLE-gcc \
    MK_CONFIGURE="--prefix=$prefix/$TRIPLE" \
    MK_DESTDIR=no \
      ./mk install bootstrap-0-musl
  fi

  if ! [ -x $prefix/bin/$TRIPLE-g++ ]; then
    build_gcc bootstrap-0-gcc-2 $prefix
  fi
}

rootfs_install() {
  local name=$1

  tar -C $ROOTFS_PREFIX -xJf repo/$(./mk query $name fullname).tar.xz
}

rootfs() {
  local prefix=$ROOTFS_PREFIX/usr

  export CC=$TRIPLE-gcc
  export CXX=$TRIPLE-g++
  export AR=$TRIPLE-ar
  export AS=$TRIPLE-as
  export LD=$TRIPLE-ld
  export RANLIB=$TRIPLE-ranlib
  export READELF=$TRIPLE-readelf
  export STRIP=$TRIPLE-strip

  ./mk pkg bootstrap-1-musl
  if ! [ -e $prefix/include/stdio.h ]; then
    rootfs_install bootstrap-1-musl
  fi

  ./mk pkg bootstrap-1-toybox
  if ! [ -x $ROOTFS_PREFIX/bin/toybox ]; then
    rootfs_install bootstrap-1-toybox
  fi

  CROSS_COMPILE=$TRIPLE- \
    ./mk pkg bootstrap-1-busybox
  if ! [ -x $ROOTFS_PREFIX/bin/busybox ]; then
    rootfs_install bootstrap-1-busybox
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr" \
    ./mk pkg bootstrap-1-binutils
  if ! [ -x $ROOTFS_PREFIX/usr/bin/ar ]; then
    rootfs_install bootstrap-1-binutils
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr" \
    ./mk pkg bootstrap-1-gmp
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libgmp.so ]; then
    rootfs_install bootstrap-1-gmp
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr
    --with-gmp=$prefix" \
    ./mk pkg bootstrap-1-mpfr
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libmpfr.so ]; then
    rootfs_install bootstrap-1-mpfr
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr
    --with-gmp=$prefix
    --with-mpfr=$prefix" \
    ./mk pkg bootstrap-1-mpc
  if ! [ -e $ROOTFS_PREFIX/usr/lib/libmpc.so ]; then
    rootfs_install bootstrap-1-mpc
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --target=$TRIPLE
    --prefix=/usr
    --with-gmp=$prefix
    --with-mpfr=$prefix
    --with-mpc=$prefix" \
    ./mk pkg bootstrap-1-gcc
  if ! [ -x $ROOTFS_PREFIX/usr/bin/gcc ]; then
    rootfs_install bootstrap-1-gcc
  fi

  MK_CONFIGURE="
    --host=$TRIPLE
    --prefix=/usr" \
    ./mk pkg bootstrap-1-make
  if ! [ -x $ROOTFS_PREFIX/usr/bin/make ]; then
    rootfs_install bootstrap-1-make
  fi

  ./mk pkg hier
  if ! [ -d $ROOTFS_PREFIX/dev ]; then
    rootfs_install hier
  fi
}

while getopts "r:x:h" opt; do
  case $opt in
    x)
      CROSS_PREFIX=$OPTARG
      ;;
    r)
      ROOTFS_PREFIX=$OPTARG
      ;;
    h)
      usage
      ;;
  esac
done

[ "$CROSS_PREFIX" ] || usage
[ "$ROOTFS_PREFIX" ] || usage

mkdir -p $CROSS_PREFIX $ROOTFS_PREFIX

TRIPLE=$(uname -m)-linux-musl

PATH=$CROSS_PREFIX/$TRIPLE/bin:$PATH

reqs
cross
rootfs
