#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

_do() {
	printf '* %s' "$@"
}

_ok() {
	printf '\n'
}

case "$1" in
	reboot)
		exit 0
		;;
	poweroff)
		exit 0
		;;
esac

cat <<"EOF"
 _
| |  Barely a linux
| |__   __ _ _ __ ___
| '_ \ / _` | '__/ _ \
| |_) | (_| | | |  __/
|_.__/ \__,_|_|  \___|

EOF

_do mounting pseudo filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
_ok

_do configuring device nodes
echo /sbin/smdev >/proc/sys/kernel/hotplug
smdev -s
_ok

_do starting ttys
for i in $(seq 5); do
	respawn /sbin/getty /dev/tty$i linux &
done
unset i
_ok
